### ISSUE TITLE
Provided docker-compose.yml might be wrong

### ISSUE THREAD

**Issue by thinkORo** [parseablehq/parseable#784] opened 2024-04-27 08:23 UTC
In your documentation for the distributed setup you mentioned your own docker-compose.yml, see: https://www.parseable.com/docs/installation-distributed/setup-distributed-parseable-on-docker-compose

I would assume that there is a typo within:

`
  parseable-query:
    image: contaianers.parseable.com/parseable/parseable:edge
`
I don't think that there is an URL like contaianers.parseable.com

**Comment by nitisht** [comment] 2024-04-27 09:42
Did you try running the compose file? The URL exists and it should work as intended

**Comment by thinkORo** [comment] 2024-04-27 11:44
Hi @nitisht, no, I didn't try that because I have my own docker-compose.yml. But I had to check the configuration in your setup for my own setup. And I thought that it's a typo.

If not: sorry for any inconvenience. And please close this ticket if the typo in the URL is as expected.

**Comment by thinkORo** [comment] 2024-04-27 11:50
And: The documentation for the standalone installtion point to a different URL without the typo: https://www.parseable.com/docs/installation/setup-parseable-on-docker

`
docker run \
  -p 8000:8000 \
  --env-file parseable-env \
  -v /parseable/staging:/staging \
  containers.parseable.com/parseable/parseable:latest \
  parseable s3-store
`

**Comment by nitisht** [comment] 2024-06-06 10:41
Thanks a lot for the pointer @thinkORo this is fixed now : https://www.parseable.com/parseable/docker-compose.yaml

Sincere apologies for the delay.

**Closed by nitisht** 2024-06-06 10:41 UTC
