### ISSUE TITLE
Unable to switch hostname

### ISSUE THREAD

**Issue by imagdy83** [parseablehq/parseable#659] opened 2024-02-16 14:54 UTC
Created streams using one hostname and configured SSL using that hostname
Now we changed the hostname and SSL won't work with the new certificate and disabling SSL doesn't work either and we get OS err 13 in the service logs

**Comment by nitisht** [comment] 2024-02-18 10:54
Hello @imagdy83 can you elaborate what did you do to disable SSL? have you tried 

```
unset P_TLS_CERT_PATH
unset P_TLS_KEY_PATH
```

**Comment by imagdy83** [comment] 2024-02-19 09:08
We are using the environment variable file which has the variables P_TLS_CERT_PATH and P_TLS_KEY_PATH so hashing them out to disable them is what I do

However now when trying to start the service even with SSL enabled I get this error
Error: Permission denied (os error 13)

**Comment by nitisht** [comment] 2024-02-19 15:29
Does the user running Parseable has write access to the `staging` path and `data` path (in case of local-store mode)? It might be helpful if you can join us on Slack to debug further - https://join.slack.com/t/parseable/shared_invite/zt-23t505gz7-zX4T10OvkS8RAhnme4gDZQ

**Comment by imagdy83** [comment] 2024-02-19 15:41
The user running parseable has access however we are using the s3 mode.
I do not have access to slack unfortunately, maybe teams?

**Comment by nitisht** [comment] 2024-02-19 15:48
> The user running parseable has access however we are using the s3 mode. I do not have access to slack unfortunately, maybe teams?

Do you mind dropping a note to nitish at parseable dot com we can set up a call.

**Comment by imagdy83** [comment] 2024-02-19 15:51
done :)

**Comment by nitisht** [comment] 2024-02-27 05:47
Hi @imagdy83 as we discussed yesterday on call, the binary seems to be working fine. The issue is with some setup / environment which probably got modified while setting up the new changes. I'll close the issue for now. Please reopen if you find out that there is an issue with the Parseable binary itself.

**Closed by nitisht** 2024-02-27 05:47 UTC
Labels: triage
