### ISSUE TITLE
Using alert webhook with Opsgenie

### ISSUE THREAD

**Issue by piellick** [parseablehq/parseable#489] opened 2023-09-08 13:29 UTC
Hello everyone,
there is a way to debug Webhook alerts ?

Opsgenie need only `message` as mandatory fields: https://docs.opsgenie.com/docs/alert-api#create-alert

we use helm charts and parseable` v0.6.2`.

i have trouble to debug my config, nothing works and nothing on output in parseable container. I have try to pass Rust logs in `info` and `debug` but nothing  related to webhook alerts.

For testing i created a match everything regex like this:

```
{
  "version": "v1",
  "alerts": [
      {
          "name": "Alert: Server side error",
          "message": "server reporting status as 500",
          "rule": {
              "type": "column",
              "config": {
                  "column": "message",
                  "operator": "~",
                  "value": "^.*$",
                  "repeats": 100,
                  "ignore_case": true
              }
          },
  "targets": [
    {
      "endpoint": "https://api.eu.opsgenie.com/v2/alerts",
      "headers": {
        "Authorization": "GenieKey XXXXXXXXXXXXXXXXXXXXXXXX"
      },
      "skip_tls_check": true,
      "type": "webhook",
      "repeat": {
        "interval": "5s",
        "times": 500
    }
    }
    ]
    }
  ]
}

```
Thanks a lot.

**Comment by nitisht** [comment] 2023-09-08 17:20
Thanks for reporting @piellick we'll take a look shortly

**Comment by piellick** [comment] 2023-09-11 08:16
hi @nitisht thanks a lot.

There is a way ti debug webhook or Print stack trace of the call ? Having alert event when rules match ? I'm a bit blind when i try to test alerts.

**Comment by trueleo** [comment] 2023-09-11 08:47
@piellick 
> There is a way ti debug webhook or Print stack trace of the call ? 
Unfortunatly none about control flow. If the target is unreachable then it should print an error warning. 

You can start off with simpler config and check against webhook.site to see if it is working 

```json
{
    "version": "v1",
    "alerts": [
        {
            "name": "Alert: Server side error",
            "message": "server reporting message {message}",
            "rule": {
                "type": "column",
                 "config": {
                      "column": "message",
                      "operator": "~",
                      "value": "^.*$",
                      "repeats": 1,
              }
            },
            "targets": [
                {
                    "type": "webhook",
                    "endpoint": "https://webhook.site/54e9af22-b667-45bf-8b95-xxxxxxxxxxxx"
                }
            ]
        }
    ]
}
```

**Comment by piellick** [comment] 2023-09-11 13:37
thanks @trueleo, nice tips :+1:

**Comment by piellick** [comment] 2023-09-15 07:16
Hi,
you right my last try with https://webhook.site/ works well, looks a problem related to opsgenie webhook implementation.

**Comment by nitisht** [comment] 2023-09-15 07:40
Thanks for letting us know @piellick

**Comment by nitisht** [comment] 2023-09-15 07:40
Should we close the issue?

**Comment by piellick** [comment] 2023-09-15 08:11
i'm not sure, generic webhook is still not working with opsgenie and i have pain to find root cause.

**Comment by nitisht** [comment] 2023-09-15 08:13
shall we get on a call to discuss / debug this

**Comment by nitisht** [comment] 2023-09-15 08:19
Do you mind joining us on Slack, we'd like to get to the root cause

**Closed** 2023-11-06 15:31 UTC
Labels: enhancement
