### ISSUE TITLE
 shorten the time from creating a log to viewing it?

### ISSUE THREAD

**Issue by jeechoul** [parseablehq/parseable#444] opened 2023-06-24 18:02 UTC
Hello, after creating a log through API, it takes about 15-30 seconds to see the log stream in the UI interface. Is this normal? How can I view it in real time, or shorten the time from creating a log to viewing it?

**Comment by nitisht** [comment] 2023-06-24 18:29
Hey @jeechoul thank you for bringing this up. This is on our roadmap for the next release. Also reported here https://github.com/parseablehq/parseable/issues/418

Please track that issue, closing this as duplicate of #418

**Closed by nitisht** 2023-06-24 18:29 UTC
